window.ONEREAD_RULES = [
  { id: "1.1", s: "Words", t: "Approved words only", d: "Use only approved words, technical nouns, or technical verbs.", b: "Utilize the robust endpoint.", a: "Use the endpoint." },
  { id: "1.2", s: "Words", t: "Listed part of speech", d: "Use an approved word only as its listed part of speech.", b: "Test the pump.", a: "Do a test of the pump." },
  { id: "1.3", s: "Words", t: "Approved meaning", d: "Use an approved word only with its approved meaning.", b: "Follow the instructions.", a: "Obey the instructions." },
  { id: "1.4", s: "Words", t: "Approved forms", d: "Use only the approved forms of verbs and adjectives.", b: "The better configuration", a: "The good configuration" },
  { id: "1.5", s: "Words", t: "Domain nouns are legal", d: "You can use domain words as technical nouns (webhook, commit, endpoint).", b: "the thing that receives events", a: "the webhook" },
  { id: "1.6", s: "Words", t: "Unapproved only inside a TN", d: "Use an unapproved word only when it is a technical noun or part of one.", b: "oil the bearing (as a verb)", a: "lubricate the bearing" },
  { id: "1.7", s: "Words", t: "Nouns are not verbs", d: "Do not use technical nouns as verbs.", b: "Webhook the event.", a: "Send the event to the webhook." },
  { id: "1.8", s: "Words", t: "Project nouns", d: "Use the technical nouns of your project or industry.", b: "the thing in YAML", a: "the configuration" },
  { id: "1.9", s: "Words", t: "Short names", d: "When you pick a technical noun, pick a short and clear one.", b: "data persistence subsystem module", a: "database" },
  { id: "1.10", s: "Words", t: "No slang", d: "No regional, slang, or jargon words as technical nouns.", b: "yeet the job", a: "cancel the job" },
  { id: "1.11", s: "Words", t: "One item, one name", d: "Do not call it config here and settings there.", b: "edit the config, then save settings", a: "edit the configuration, then save the configuration" },
  { id: "1.12", s: "Words", t: "Domain verbs are legal", d: "You can use domain verbs as technical verbs (deploy, compile, merge).", b: "do a deploy", a: "deploy the service" },
  { id: "1.13", s: "Words", t: "Verbs are not nouns", d: "Do not use technical verbs as nouns.", b: "do a rollback", a: "roll back the deploy" },
  { id: "1.14", s: "Words", t: "American spelling", d: "Use American English spelling.", b: "colour, initialise", a: "color, initialize" },
  { id: "2.1", s: "Nouns", t: "Three-word chains", d: "Write multi-word nouns of three words or fewer.", b: "the connection pool timeout configuration value", a: "the timeout value for the connection pool" },
  { id: "2.2", s: "Nouns", t: "Introduce long names once", d: "Write a long technical noun in full once, then give a short form.", b: "Simple Notification Service every time", a: "Simple Notification Service (SNS), then SNS" },
  { id: "3.1", s: "Verbs", t: "Dictionary verb forms", d: "Use only the verb forms that the dictionary gives.", b: "The file was being written.", a: "The system writes the file." },
  { id: "3.2", s: "Verbs", t: "Simple tenses only", d: "Infinitive, imperative, simple present, simple past, simple future. Banned modals: should, would, may, might, could.", b: "You should restart.", a: "Restart the service." },
  { id: "3.3", s: "Verbs", t: "Past participle as adjective", d: "Use the past participle only as an adjective.", b: "The response has cached.", a: "the cached response" },
  { id: "3.4", s: "Verbs", t: "No complex auxiliaries", d: "No present perfect. No is to be installed.", b: "The migration has completed.", a: "The migration is complete." },
  { id: "3.5", s: "Verbs", t: "No -ing as a verb", d: "-ing is legal as a technical noun (logging), never as a verb clause.", b: "The flag can be set, making restarts unnecessary.", a: "You can set the flag. Then a restart is not necessary." },
  { id: "3.6", s: "Verbs", t: "Active voice", d: "Passive is legal in descriptions only when the agent is unknown.", b: "The temperature must be adjusted.", a: "Adjust the temperature." },
  { id: "3.7", s: "Verbs", t: "Verb, not noun", d: "Describe an action with a verb, not a noun.", b: "perform compression of the file", a: "compress the file" },
  { id: "4.1", s: "Sentences", t: "Short and clear", d: "Write short and clear sentences.", b: "A 40-word sentence with three clauses.", a: "Two or three short sentences." },
  { id: "4.2", s: "Sentences", t: "Complete grammar", d: "No contractions. Keep articles. Keep that.", b: "Ensure file exists before running.", a: "Make sure that the file exists before you run the command." },
  { id: "4.3", s: "Sentences", t: "Vertical lists", d: "Use a vertical list for complex text.", b: "Do A, B, C, and D in one sentence.", a: "A numbered list of four steps." },
  { id: "4.4", s: "Sentences", t: "Connecting words", d: "Use connecting words between related sentences (Then, As a result).", b: "Stop. Copy. Start.", a: "Stop the service. Then copy the backup. Then start the service." },
  { id: "4.5", s: "Sentences", t: "Articles", d: "Put an article or a demonstrative before nouns where applicable.", b: "Copy backup to folder.", a: "Copy the backup to the folder." },
  { id: "5.1", s: "Procedures", t: "20-word limit", d: "Maximum 20 words per sentence, warnings included.", b: "A 28-word instruction.", a: "Two instructions under 20 words." },
  { id: "5.2", s: "Procedures", t: "One instruction", d: "One instruction per sentence, unless two actions happen at the same time.", b: "Stop the service and copy the backup.", a: "Stop the service. Then copy the backup." },
  { id: "5.3", s: "Procedures", t: "Imperative", d: "Write instructions in the imperative.", b: "The user should run the migration.", a: "Run the migration." },
  { id: "5.4", s: "Procedures", t: "Condition first", d: "Put a required condition before the command, divided by a comma.", b: "Read the log if the build fails.", a: "If the build fails, read the log." },
  { id: "5.5", s: "Procedures", t: "Notes are not commands", d: "Notes give information, never instructions. Notes get the 25-word limit.", b: "NOTE: Restart the node.", a: "NOTE: The default timeout is 30 s." },
  { id: "6.1", s: "Descriptions", t: "One new fact", d: "Give information gradually: one new fact per sentence.", b: "Three facts in one sentence.", a: "Three sentences." },
  { id: "6.2", s: "Descriptions", t: "Key words", d: "Use key words and phrases to give the text a logical structure.", b: "Also, additionally, furthermore", a: "First. Then. As a result." },
  { id: "6.3", s: "Descriptions", t: "25-word limit", d: "Maximum 25 words per sentence.", b: "A 33-word description.", a: "Two sentences under 25 words." },
  { id: "6.4", s: "Descriptions", t: "Group related facts", d: "Group related information in paragraphs.", b: "Mixed topics in one block.", a: "One topic per paragraph." },
  { id: "6.5", s: "Descriptions", t: "One topic", d: "One topic per paragraph.", b: "Timeouts and billing in one paragraph.", a: "A paragraph on timeouts. A paragraph on billing." },
  { id: "6.6", s: "Descriptions", t: "Six sentences max", d: "Maximum six sentences per paragraph.", b: "An eight-sentence wall.", a: "Two paragraphs." },
  { id: "7.1", s: "Safety", t: "Signal word", d: "WARNING = injury or death. CAUTION = damage to equipment or data. NOTE = information only.", b: "Note that data loss may occur.", a: "CAUTION: Do not use --force against production. The flag deletes rows." },
  { id: "7.2", s: "Safety", t: "Command first", d: "Start with a clear command or condition.", b: "Data loss can occur if you use --force.", a: "CAUTION: Do not use --force against production." },
  { id: "7.3", s: "Safety", t: "Then the risk", d: "Then give the risk or the possible result.", b: "A command with no risk stated.", a: "The flag deletes rows that do not match the source." },
  { id: "8.1", s: "Count", t: "No semicolon", d: "All standard punctuation is legal except the semicolon. No em dashes.", b: "Stop; then copy.", a: "Stop. Then copy." },
  { id: "8.2", s: "Count", t: "Hyphens as one unit", d: "Use hyphens to connect words that act as one unit.", b: "the read only file", a: "the read-only file" },
  { id: "8.3", s: "Count", t: "Parentheses", d: "Parentheses are legal for references, abbreviations, explanations.", b: "the timeout (see above)", a: "the timeout (30 s)" },
  { id: "8.4", s: "Count", t: "List colon ends a sentence", d: "In a vertical list, the lead-in colon ends a sentence for word count.", b: "A 40-word lead-in with items.", a: "Do the steps that follow:" },
  { id: "8.5", s: "Count", t: "Parenthetical text", d: "Text inside parentheses counts as one word.", b: "counting every inner word", a: "one word for the parenthesis" },
  { id: "8.6", s: "Count", t: "Identifiers count as one", d: "Numbers with units, abbreviations, quoted text, and identifiers count as one word.", b: "sqlpipe run --config sqlpipe.yaml blows the budget", a: "the backticked command counts as one word" },
  { id: "8.7", s: "Count", t: "Hyphenated = one", d: "A hyphenated word counts as one word.", b: "read only as two", a: "read-only as one" },
  { id: "9.1", s: "Practice", t: "Restructure, do not swap", d: "When a word-for-word replacement does not work, restructure the sentence.", b: "Before accept of the unit", a: "Before you accept the unit, do the specified test." },
  { id: "9.2", s: "Practice", t: "Use the approved meaning", d: "Use each approved word correctly: approved meaning, approved part of speech.", b: "help as a noun", a: "with the aid of" },
  { id: "9.3", s: "Practice", t: "No phrasal verbs", d: "Do not build phrasal verbs.", b: "set up the cluster", a: "configure the cluster" },
  { id: "9.4", s: "Practice", t: "One style", d: "Keep one consistent style and terminology through the whole document.", b: "run, execute, invoke, launch", a: "pick one verb and keep it" }
];
